---
# tasks file for common

- name: Common Packages
  ansible.builtin.include_tasks: packages.yml

- name: Adding hosts to hosts
  ansible.builtin.include_tasks: naming.yml
  when: common_enabled_hosts_naming is defined and common_enabled_hosts_naming == true
