# unencrypted as an example
postgres_host: "192.168.56.10"
postgres_port: 5432
postgres_db: postgres
postgres_user: postgres
postgres_password: postgres

minio_user: minioadmin
minio_password: minioadmin