# unencrypted as an example
postgres_host: 192.168.0.96
postgres_port: 5432
postgres_db: postgres
postgres_user: postgres
postgres_password: postgres

minio_user: minioadmin
minio_password: minioadmin

grafana_user: admin
grafana_password: admin
