all:
  children:
    webservers:
      hosts:
        web01.example.test:
          ansible_host: app-host.example.test
          enable_node_exporter: true
    workers:
      hosts:
        worker01.example.test:
          ansible_host: app-host.example.test
    db:
      hosts:
        db01.example.test:
          ansible_host: app-host.example.test
    s3:
      hosts:
        s3.example.test:
          ansible_host: app-host.example.test

    prometheus:
      hosts:
        prometheus.example.test:
          ansible_host: monitoring.example.test
          enable_node_exporter: true
    alertmanager:
      hosts:
        alertmanager.example.test:
          ansible_host: monitoring.example.test
    grafana:
      hosts:
        grafana.example.test:
          ansible_host: monitoring.example.test
    loki:
      hosts:
        loki.example.test:
          ansible_host: monitoring.example.test
