---
- name: All Servers Preparation
  hosts: all
  become: true
  tags:
    - common
  roles:
    - role: common
    - role: docker
    - role: grafana.grafana.promtail

- name: Loki Deployment
  hosts: loki
  become: true
  tags:
    - loki
  pre_tasks:
    - name: Creating Conf Dir
      ansible.builtin.file:
        path: "{{ container_conf_dir }}"
        state: directory
        mode: "0750"
    - name: Creating Data Dir
      ansible.builtin.file:
        path: "{{ container_data_dir }}"
        state: directory
        owner: "{{ loki_user_id }}"
        group: "{{ loki_group_id }}"
  roles:
    - role: container

- name: Prometheus Deployment
  hosts: prometheus
  become: true
  tags:
    - prometheus
  pre_tasks:
    - name: Creating Conf Dir
      ansible.builtin.file:
        path: "{{ container_conf_dir }}"
        state: directory
        mode: "0750"
    - name: Creating Data Dir
      ansible.builtin.file:
        path: "{{ container_data_dir }}"
        state: directory
        owner: "{{ prometheus_user_id }}"
        group: "{{ prometheus_group_id }}"
    - name: Prometheus Config
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/prometheus.yml.j2"
        dest: "{{ container_conf_dir }}/prometheus.yml"
  roles:
    - role: container


- name: Grafana Deployment
  hosts: grafana
  become: true
  tags:
    - grafana
  pre_tasks:
    - name: Creating Conf Dir
      ansible.builtin.file:
        path: "{{ container_conf_dir }}/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - datasources
        - dashboards
    - name: Creating Data Dir
      ansible.builtin.file:
        path: "{{ container_data_dir }}"
        state: directory
        owner: "{{ grafana_user_id }}"
        group: "{{ grafana_group_id }}"
    - name: Grafana Datasource Provisioners
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/grafana/datasources/datasources.yml.j2"
        dest: "{{ container_conf_dir }}/datasources/datasources.yml"
    - name: Grafana Dashboards Provisioners
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/grafana/dashboards.yml"
        dest: "{{ container_conf_dir }}/dashboards/dashboards.yml"
    - name: Copy Dashboards
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../templates/grafana/dashboards/"
        dest: "{{ container_data_dir }}/dashboards/"
        owner: "{{ grafana_user_id }}"
        group: "{{ grafana_group_id }}"
        mode: '0755'
  roles:
    - role: container

- name: Alertmanager Deployment
  hosts: alertmanager
  become: true
  tags:
    - alertmanager
  pre_tasks:
    - name: Creating Conf Dir
      ansible.builtin.file:
        path: "{{ container_conf_dir }}"
        state: directory
        mode: "0750"
    - name: Creating Data Dir
      ansible.builtin.file:
        path: "{{ container_data_dir }}"
        state: directory
        owner: "{{ alertmanager_user_id }}"
        group: "{{ alertmanager_group_id }}"
    - name: Alertmanager Config
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/alertmanager.yml.j2"
        dest: "{{ container_conf_dir }}/alertmanager.yml"
  roles:
    - role: container

- name: Nginx Prometheus Exporter Deployment
  hosts: webservers
  become: true
  tags:
    - nginx-exporter
  roles:
    - role: container